dist: precise

jdk:
  - oraclejdk7

before_script:
  - cp .travis.settings.xml ${HOME}/.m2/settings.xml

script:
  - mvn -Dhttps.protocols=TLSv1.2 clean install

deploy:
  - provider: script
    skip_cleanup: true
    script: mvn --quiet sonar:sonar -DskipTests
    on:
      branch: development
