dist: trusty

language: java

jdk:
  - oraclejdk8

git:
  depth: false

cache:
  directories:
    - $HOME/.m2

before_script:
  - cp .travis.settings.xml ${HOME}/.m2/settings.xml

script:
  - mvn clean install

deploy:
  - provider: script
    skip_cleanup: true
    script: bash sonar-scanner.sh
    on:
      all_branches: true
