dist: trusty

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_script:
  - cp .travis.settings.xml ${HOME}/.m2/settings.xml

script:
  - mvn clean install

deploy:
  - provider: script
    skip_cleanup: true
    script: mvn -DskipTests sonar:sonar
    on:
      branch: development
